name: Keep Main Pretty
# these are a series of jobs that auto-update main as needed

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pretty-main
  cancel-in-progress: true

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - run: ruff check --fix
      - run: ruff format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Linter 🧹


  test-coverage:
    name: pytest
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/214217882291/locations/global/workloadIdentityPools/github-actions-pool-bigquery/providers/github-provider-sl'
          service_account: 'bigquery-github-actions@luke-test-project-461115.iam.gserviceaccount.com'

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest --cov=src/bigquery_mcp tests

      - name: generate coverage badge
        run: uv run coverage-badge -o tests/coverage.svg -f

      - name: commit changes and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Test Coverage 📈
